// SPDX-License-Identifier: MIT
pragma solidity ^0.7.0;

// KeeperCompatible.sol imports the functions from both ./KeeperBase.sol and

import "@chainlink/contracts/src/v0.7/KeeperCompatible.sol";
import "https://github.com/moltd/spudsfo/edit/master/chainlink/AccuweatherConsumer" // get weather data from AccuWeather 
// should this be in line as another contsract block?

contract BuilderKeeperContract is KeeperCompatibleInterface {
    /**
    * Public counter variable
    */
    uint public daysMissed;
    uint public precipRate24;

    /**
    * Use an interval in seconds and a timestamp to slow execution of Upkeep
    */
    uint public immutable interval;
    uint public lastTimeStamp;
    
    AccuweatherConsumer internal accuWeatherFeed;
    
    /** LINK, Oracle and JobIDs for AccuWeather */
    string internal accuW_Link = "0xa36085F69e2889c224210F603D836748e7dC0088";
    string internal accuW_Oracle = "0xfF07C97631Ff3bAb5e5e5660Cdf47AdEd8D4d4Fd";
    string internal accuW_jobID = "7c276986e23b4b1c990d8659bca7a9d0" // location-current-conditions
    struct internal CurrentConditionResult result;

    
    /** JobSite LONG / LAT **/
    uint internal jobsite_LAT = 37;
    uint internal jobsite_LONG = -122; 

    constructor(uint updateInterval) {
    
      // Realitically for our use case we only need to this contract unkeep once every 24 hours, but for the test instance we will do every 15 seconds
  
      interval = updateInterval;
      lastTimeStamp = block.timestamp;
      daysMissed = 0;
      
      accuWeatherFeed = AccuweatherConsumer(accuW_Link, accuW_Oracle);
    }

    function getWeatherPrecipRate() {
         result = accuWeatherFeed.requestLocationCurrentConditions(
            accuW_jobID,
            accuW_Link,
            string jobsite_LAT,
            string jobsite_LONG,
            string units);
            
         return result.preciptationPast24Hours;
    }

    function checkUpkeep(bytes calldata /* checkData */) external override returns (bool upkeepNeeded, bytes memory /* performData */) {
   
        uint precipRate24 = getWeatherPrecipRate();
        upkeepNeeded = ((getWeatherPrecipRate()) > 1.5); // abstract 1.5 to checkData parameter.
      
        // upkeepNeeded = (block.timestamp - lastTimeStamp) > interval;
        // We don't use the checkData in this example. The checkData is defined when the Upkeep was registered.
    }

    function performUpkeep(bytes calldata /* performData */) external override {
    
        lastTimeStamp = block.timestamp;
        
        // need a month block
        if (lastTimeStamp > 30 days) {
            daysMissed = 0;
        }
        
        if (lastTimeStamp > 1 days) {
            daysMissed = daysMissed + 1; // exceeded the rain threshold, in a month
        }
        
        if (daysMissed > 3) {
            // liquidate
        }
        
        // We don't use the performData in this example. The performData is generated by the Keeper's call to your checkUpkeep function
    }
}
